# Generated by Django 5.2.4 on 2025-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
